name: Build prefect docker images

# Note: Conda support for 3.11 is pending. See https://github.com/ContinuumIO/anaconda-issues/issues/13082

on:
  # On release events (also when a published release is converted from/to prerelease), push all patterns
  release:
    types: [released, prereleased]
  # On each commit merged into main, push sha and branch patterns to prefect-dev
  push:
    branches: main
  # On workflow_dispatch, push sha and branch patterns to prefect-dev
  workflow_dispatch:

jobs:
  publish-docker-images:
    name: Build Docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor:
          - ""
          - "-conda"
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        exclude:
          # Not yet supported, see note at top
          - flavor: "-conda"
            python-version: "3.11"

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Export CURRENT_BRANCH env var
        # github.ref_name points to e.g. '2.6.9' on release, so need to parse from git
        run: echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Generate tags for prefecthq/prefect-dev
        id: metadata-dev
        uses: docker/metadata-action@v4
        with:
          images: prefecthq/prefect-dev
          # list the branch pattern first, to use as CACHE_IMAGE below
          tags: |
            type=raw,value=${{ env.CURRENT_BRANCH }},suffix=-python${{ matrix.python-version }}${{ matrix.flavor }}
            type=sha,suffix=-python${{ matrix.python-version }}${{ matrix.flavor }}
          flavor: |
            latest=false

      - name: Generate tags for prefecthq/prefect
        id: metadata-prod
        uses: docker/metadata-action@v4
        with:
          images: prefecthq/prefect,enable=${{ github.event_name == 'release' }}
          tags: |
            type=raw,enable=${{ matrix.python-version == '3.10' }},value=2-latest${{ matrix.flavor }}
            type=pep440,pattern={{version}},suffix=-python${{ matrix.python-version }}${{ matrix.flavor }}
            type=pep440,pattern={{major}}.{{minor}},suffix=-python${{ matrix.python-version }}${{ matrix.flavor }}
            type=pep440,pattern={{major}},suffix=-python${{ matrix.python-version }}${{ matrix.flavor }}
          flavor: |
            latest=false

      # always use prefect-dev branch pattern for layer caching
      - name: Export CACHE_IMAGE env var
        run: echo "CACHE_IMAGE=$(echo '${{ steps.metadata-dev.outputs.json }}' | jq -r '.tags[0]')" >> $GITHUB_ENV

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            ${{ ( endsWith(matrix.flavor, 'conda') && 'BASE_IMAGE=prefect-conda' ) || '' }}
          tags: ${{ join(steps.metadata-dev.outputs.tags) }},${{ join(steps.metadata-prod.outputs.tags) }}
          labels: ${{ steps.metadata-dev.outputs.labels }}
          push: true
          # cache images need additional suffix because they are not usable for runtime
          cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}-buildcache
          cache-to: type=registry,ref=${{ env.CACHE_IMAGE }}-buildcache,mode=max

      - name: Test docker image
        run: docker run --rm ${{ env.CACHE_IMAGE }} prefect version
